syntax = "proto3";


package GY.SECS;

import "common.proto";

// 被动接收接口定义（本项目作为 gRPC Server）。
// 说明：本文件存放“外部系统调用本项目”的所有 RPC。

// 结果上报服务。
service ReportGrpcService {
	// 设备获取晶圆盒后，Mapping结束后上报RFID和Mapping结果。
	rpc ReportRFID (.GY.EFEM.CarrierMessage) returns (.GY.EFEM.ReportReply);
	
	// 外部上报检测结果。
	rpc ResultReport (.GY.EFEM.WaferMessage) returns (.GY.EFEM.ReportReply);

	// 外部上报状态
	rpc StatusReport (.GY.EFEM.StatusMessage) returns (.GY.EFEM.StatusReply);

	// 外部上报报警（报警发生）。
	rpc ReportAlarm (.GY.EFEM.AlarmReportRequest) returns (.GY.EFEM.AlarmReply);
}

