<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Secs4Net\Secs4Net.csproj" />
    <ProjectReference Include="..\..\Builders\SECSbuilder\SECSbuilder.csproj" />
    <ProjectReference Include="..\..\Models\SECSdata\SECSdata.csproj" />
    <ProjectReference Include="..\..\Parsers\SECSparser\SECSparser.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GY.PLC.Comm" Version="2.2.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>

</Project>
