namespace GY.PLC.Comm
{
    /// <summary>
    /// This class is generated by the GY.PLC.Comm.Generator.
    /// </summary>
    public class Plc
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Plc"/> Coils .
        /// </summary>
        public class Coils
        {
            /// <summary>
            /// Coil: 工作模式, Default: false.
            /// </summary>
            public const ushort WorkModel = 8008;

            /// <summary>
            /// Coil: 系统停止, Default: true.
            /// </summary>
            public const ushort SystemStop = 8009;

            /// <summary>
            /// Coil: 系统初始化, Default: false.
            /// </summary>
            public const ushort SystemInitial = 8010;

            /// <summary>
            /// Coil: 系统启动, Default: true.
            /// </summary>
            public const ushort SystemStart = 8011;

            /// <summary>
            /// Coil: 系统心跳, Default: false.
            /// </summary>
            public const ushort SystemHeartbeat = 8012;

            /// <summary>
            /// Coil: EFU1速度设定发送, Default: false.
            /// </summary>
            public const ushort EFU1SpeedSet = 8013;

            /// <summary>
            /// Coil: EFU2速度设定发送, Default: false.
            /// </summary>
            public const ushort EFU2SpeedSet = 8014;

            /// <summary>
            /// Coil: Robot单工位停止, Default: false.
            /// </summary>
            public const ushort RobotStop = 8016;

            /// <summary>
            /// Coil: Robot单工位复位, Default: false.
            /// </summary>
            public const ushort RobotReset = 8017;

            /// <summary>
            /// Coil: Robot单工位启动, Default: false.
            /// </summary>
            public const ushort RobotEnable = 8018;

            /// <summary>
            /// Coil: LoadPort单工位停止, Default: false.
            /// </summary>
            public const ushort LoadPortStop = 8019;

            /// <summary>
            /// Coil: LoadPort单工位复位, Default: false.
            /// </summary>
            public const ushort LoadPortReset = 8020;

            /// <summary>
            /// Coil: LoadPort单工位启动, Default: false.
            /// </summary>
            public const ushort LoadPortStart = 8021;

            /// <summary>
            /// Coil: Aligner单工位停止, Default: false.
            /// </summary>
            public const ushort AlignerStop = 8022;

            /// <summary>
            /// Coil: Aligner单工位复位, Default: false.
            /// </summary>
            public const ushort AlignerReset = 8023;

            /// <summary>
            /// Coil: Aligner单工位启动, Default: false.
            /// </summary>
            public const ushort AlignerEnable = 8024;

            /// <summary>
            /// Coil: 边缘STAGE停止, Default: false.
            /// </summary>
            public const ushort EdgeStop = 8025;

            /// <summary>
            /// Coil: 边缘STAGE复位, Default: false.
            /// </summary>
            public const ushort EdgeReset = 8026;

            /// <summary>
            /// Coil: 边缘STAGE启动, Default: false.
            /// </summary>
            public const ushort EdgeEnable = 8027;

            /// <summary>
            /// Coil: 正表面STAGE停止, Default: false.
            /// </summary>
            public const ushort BSStop = 8028;

            /// <summary>
            /// Coil: 正表面STAGE复位, Default: false.
            /// </summary>
            public const ushort BSReset = 8029;

            /// <summary>
            /// Coil: 正表面STAGE启动, Default: false.
            /// </summary>
            public const ushort BSEnable = 8030;

            /// <summary>
            /// Coil: 当前轴使能, Default: false.
            /// </summary>
            public const ushort CurrentAxisEnable = 8168;

            /// <summary>
            /// Coil: 当前轴停止, Default: false.
            /// </summary>
            public const ushort CurrentAxisStop = 8169;

            /// <summary>
            /// Coil: 当前轴复位, Default: false.
            /// </summary>
            public const ushort CurrentAxisReset = 8170;

            /// <summary>
            /// Coil: 当前轴回零, Default: false.
            /// </summary>
            public const ushort CurrentAxisIdle = 8171;

            /// <summary>
            /// Coil: 当前轴JOG+, Default: false.
            /// </summary>
            public const ushort CurrentAxisJogPlus = 8172;

            /// <summary>
            /// Coil: 当前轴JOG-, Default: false.
            /// </summary>
            public const ushort CurrentAxisJogMinus = 8173;

            /// <summary>
            /// Coil: 当前轴绝对定位, Default: false.
            /// </summary>
            public const ushort CurrentAxisAbsoluteMove = 8174;

            /// <summary>
            /// Coil: 当前轴相对定位正转, Default: false.
            /// </summary>
            public const ushort CurrentAxisRelativeForward = 8175;

            /// <summary>
            /// Coil: 当前轴相对定位反转, Default: false.
            /// </summary>
            public const ushort CurrentAxisRelativeBackward = 8176;

            /// <summary>
            /// Coil: 当前轴使能中, Default: false.
            /// </summary>
            public const ushort CurrentAxisEnabling = 8177;

            /// <summary>
            /// Coil: 当前轴回零中, Default: false.
            /// </summary>
            public const ushort CurrentAxisStopping = 8178;

            /// <summary>
            /// Coil: 当前轴回零完成, Default: false.
            /// </summary>
            public const ushort CurrentAxisStopFinish = 8179;

            /// <summary>
            /// Coil: 当前轴定位中, Default: false.
            /// </summary>
            public const ushort CurrentAxisLocating = 8180;

            /// <summary>
            /// Coil: 当前轴定位完成, Default: false.
            /// </summary>
            public const ushort CurrentAxisLocateFinish = 8181;

            /// <summary>
            /// Coil: 当前轴错误, Default: false.
            /// </summary>
            public const ushort CurrentAxisErrMsg = 8182;

            /// <summary>
            /// Coil: PLC请求Notch拍照, Default: false.
            /// </summary>
            public const ushort PlcRequestTakePhotoNotch = 8328;

            /// <summary>
            /// Coil: PC告知PLCNotch拍照完成, Default: false.
            /// </summary>
            public const ushort PcTellPlcTakePhotoNotchDone = 8329;

            /// <summary>
            /// Coil: PLC请求Edge拍照, Default: false.
            /// </summary>
            public const ushort PlcRequestTakePhotoEdge = 8330;

            /// <summary>
            /// Coil: PC告知PlcEdge光源已开, Default: false.
            /// </summary>
            public const ushort PcTellPlcOpenLightForEdgeDone = 8331;

            /// <summary>
            /// Coil: PLC告知PCEdge拍照完成, Default: false.
            /// </summary>
            public const ushort PlcTellPcTakePhotoEdgeFinished = 8332;

            /// <summary>
            /// Coil: PLC请求Surface拍照, Default: false.
            /// </summary>
            public const ushort PlcRequestTakePhotoSurface = 8333;

            /// <summary>
            /// Coil: PC告知PlcSurface光源已开, Default: false.
            /// </summary>
            public const ushort PcTellPlcOpenLightForSurfaceDone = 8334;

            /// <summary>
            /// Coil: Plc告知PCSurface拍照完成, Default: false.
            /// </summary>
            public const ushort PlcTellPcTakePhotoForSurfaceFinished = 8335;

            /// <summary>
            /// Coil: LoadPort1门打开, Default: false.
            /// </summary>
            public const ushort LoadPort1OpenDoorFinish = 8336;

            /// <summary>
            /// Coil: LoadPort1门关闭, Default: false.
            /// </summary>
            public const ushort LoadPort1CloseDoorFinish = 8337;

            /// <summary>
            /// Coil: LoadPort2门打开, Default: false.
            /// </summary>
            public const ushort LoadPort2OpenDoorFinish = 8338;

            /// <summary>
            /// Coil: LoadPort2门关闭, Default: false.
            /// </summary>
            public const ushort LoadPort2CloseDoorFinish = 8339;

            /// <summary>
            /// Coil: LoadPort3门打开, Default: false.
            /// </summary>
            public const ushort LoadPort3OpenDoorFinish = 8340;

            /// <summary>
            /// Coil: LoadPort3门关闭, Default: false.
            /// </summary>
            public const ushort LoadPort3CloseDoorFinish = 8341;

            /// <summary>
            /// Coil: LoadPort4门打开, Default: false.
            /// </summary>
            public const ushort LoadPort4OpenDoorFinish = 8342;

            /// <summary>
            /// Coil: LoadPort4门关闭, Default: false.
            /// </summary>
            public const ushort LoadPort4CloseDoorFinish = 8343;

            /// <summary>
            /// Coil: 单片晶圆检测开始, Default: false.
            /// </summary>
            public const ushort PlcTestStart = 8344;

            /// <summary>
            /// Coil: 单片晶圆检测完成, Default: false.
            /// </summary>
            public const ushort PlcTestDone = 8345;

            /// <summary>
            /// Coil: Surface工位有板, Default: false.
            /// </summary>
            public const ushort SurfaceStationHasWafer = 8346;

            /// <summary>
            /// Coil: Edge工位有板, Default: false.
            /// </summary>
            public const ushort EdgeStationHasWafer = 8347;

            /// <summary>
            /// Coil: Plc请求aligner拍照, Default: false.
            /// </summary>
            public const ushort PlcRequestTakePhotoWaferId = 8348;

            /// <summary>
            /// Coil: PC告知Plcaligner拍照完成, Default: false.
            /// </summary>
            public const ushort PcTellPlcTakePhotoWaferIdFinished = 8349;

            /// <summary>
            /// Coil: aligner工位本机有板, Default: false.
            /// </summary>
            public const ushort AlignerHasWafer = 8350;

            /// <summary>
            /// Coil: Wafer id 位置, Default: false.
            /// </summary>
            public const ushort WaferIdSide = 8356;

            /// <summary>
            /// Coil:PC发送Plc自动换盒, Default: false.
            /// </summary>
            public const ushort PCTellPlcFoupAutoExchange = 8366;

            /// <summary>
            /// Coil: EdgeLightArch灯光亮度设置完成, Default: false.
            /// </summary>
            public const ushort EdgeLightArchChanged = 8371;

            /// <summary>
            /// Coil: EdgeLightDot灯光亮度设置完成，Default: false.
            /// </summary>
            public const ushort EdgeLightDotChanged = 8372;

            /// <summary>
            /// Coil: RecheckLightUp灯光亮度设置完成，Default: false.
            /// </summary>
            public const ushort RecheckLightUpChanged = 8373;

            /// <summary>
            /// Coil: RecheckLightDown灯光亮度设置完成，Default: false.
            /// </summary>
            public const ushort RecheckLightDownChanged = 8374;

            /// <summary>
            /// Coil: RB命令开始, Default: false.
            /// </summary>
            public const ushort RobotCommandStart = 8648;

            /// <summary>
            /// Coil: RB执行中, Default: false.
            /// </summary>
            public const ushort RobotCommandOngoing = 8649;

            /// <summary>
            /// Coil: ARM1 Wafer有无, Default: false.
            /// </summary>
            public const ushort Arm1HasWafer = 8650;

            /// <summary>
            /// Coil: ARM2 Wafer有无, Default: false.
            /// </summary>
            public const ushort Arm2HasWafer = 8651;

            /// <summary>
            /// Coil: RB错误, Default: false.
            /// </summary>
            public const ushort RobotErrMsg = 8652;

            /// <summary>
            /// Coil: LP1命令开始, Default: false.
            /// </summary>
            public const ushort LoadPort1CommandStart = 8808;

            /// <summary>
            /// Coil: LP2命令开始, Default: false.
            /// </summary>
            public const ushort LoadPort2CommandStart = 8809;

            /// <summary>
            /// Coil: LP3命令开始, Default: false.
            /// </summary>
            public const ushort LoadPort3CommandStart = 8810;

            /// <summary>
            /// Coil: LP4命令开始, Default: false.
            /// </summary>
            public const ushort LoadPort4CommandStart = 8811;

            /// <summary>
            /// Coil: LP1Cassette有无, Default: false.
            /// </summary>
            public const ushort LoadPort1HasCassette = 8812;

            /// <summary>
            /// Coil: LP2Cassette有无, Default: false.
            /// </summary>
            public const ushort LoadPort2HasCassette = 8813;

            /// <summary>
            /// Coil: LP3Cassette有无, Default: false.
            /// </summary>
            public const ushort LoadPort3HasCassette = 8814;

            /// <summary>
            /// Coil: LP4Cassette有无, Default: false.
            /// </summary>
            public const ushort LoadPort4HasCassette = 8815;

            /// <summary>
            /// Coil: LP1执行中, Default: false.
            /// </summary>
            public const ushort LoadPort1CommandOngoing = 8816;

            /// <summary>
            /// Coil: LP2执行中, Default: false.
            /// </summary>
            public const ushort LoadPort2CommandOngoing = 8817;

            /// <summary>
            /// Coil: LP3执行中, Default: false.
            /// </summary>
            public const ushort LoadPort3CommandOngoing = 8818;

            /// <summary>
            /// Coil: LP4执行中, Default: false.
            /// </summary>
            public const ushort LoadPort4CommandOngoing = 8819;

            /// <summary>
            /// Coil: LP1错误, Default: false.
            /// </summary>
            public const ushort LoadPort1ErrMsg = 8820;

            /// <summary>
            /// Coil: LP2错误, Default: false.
            /// </summary>
            public const ushort LoadPort2ErrMsg = 8821;

            /// <summary>
            /// Coil: LP3错误, Default: false.
            /// </summary>
            public const ushort LoadPort3ErrMsg = 8822;

            /// <summary>
            /// Coil: LP4错误, Default: false.
            /// </summary>
            public const ushort LoadPort4ErrMsg = 8823;

            /// <summary>
            /// Coil: ALN命令开始, Default: false.
            /// </summary>
            public const ushort AlignerCommandStart = 8968;

            /// <summary>
            /// Coil: ALN执行中, Default: false.
            /// </summary>
            public const ushort AlignerCommandOngoing = 8969;

            /// <summary>
            /// Coil: ALN错误, Default: false.
            /// </summary>
            public const ushort AlignerErrMsg = 8971;

            /// <summary>
            /// Coil: 当前气缸动作, Default: false.
            /// </summary>
            public const ushort CurrentBSCylinderAction = 9128;

            /// <summary>
            /// Coil: 当前气缸复位, Default: false.
            /// </summary>
            public const ushort CurrentCylinderEnable = 9129;

            /// <summary>
            /// Coil: 当前气缸到位, Default: false.
            /// </summary>
            public const ushort CurrentCylinderFeedback = 9130;

            /// <summary>
            /// Coil: 当前气缸原位, Default: false.
            /// </summary>
            public const ushort CurrentCylinderOriginalPos = 9131;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Plc"/> Holdings.
        /// </summary>
        public class Holdings
        {
            /// <summary>
            /// Holding: 系统状态字, Default: 0.
            /// </summary>
            public const ushort PlcStatusAddress = 1000;

            /// <summary>
            /// Holding: EFU1开关, Default: 0.
            /// </summary>
            public const ushort EFU1Switch = 1001;

            /// <summary>
            /// Holding: EFU1档位, Default: 0.
            /// </summary>
            public const ushort EFU1Gear = 1002;

            /// <summary>
            /// Holding: EFU1开关反馈, Default: 0.
            /// </summary>
            public const ushort EFU1SwitchFeedback = 1003;

            /// <summary>
            /// Holding: EFU1档位反馈, Default: 0.
            /// </summary>
            public const ushort EFU1GearFeedback = 1004;

            /// <summary>
            /// Holding: EFU2开关, Default: 0.
            /// </summary>
            public const ushort EFU2Switch = 1005;

            /// <summary>
            /// Holding: EFU2档位, Default: 0.
            /// </summary>
            public const ushort EFU2Gear = 1006;

            /// <summary>
            /// Holding: EFU2开关反馈, Default: 0.
            /// </summary>
            public const ushort EFU2SwitchFeedback = 1007;

            /// <summary>
            /// Holding: EFU2档位反馈, Default: 0.
            /// </summary>
            public const ushort EFU2GearFeedback = 1008;

            /// <summary>
            /// Holding: Robot单工位报警代码, Default: 0.
            /// </summary>
            public const ushort RobotErrorCode = 1009;

            /// <summary>
            /// Holding: LP单工位报警代码, Default: 0.
            /// </summary>
            public const ushort LpErrorCode = 1010;

            /// <summary>
            /// Holding: ALN单工位报警代码, Default: 0.
            /// </summary>
            public const ushort AlnErrorCode = 1011;

            /// <summary>
            /// Holding: STAGE单工位报警代码, Default: 0.
            /// </summary>
            public const ushort EdgeStageErrorCode = 1012;

            /// <summary>
            /// Holding: STAGE单工位报警代码, Default: 0.
            /// </summary>
            public const ushort SurfaceStageErrorCode = 1013;

            /// <summary>
            /// Holding: 指定轴ID, Default: 0.
            /// </summary>
            public const ushort SelectAxisId = 1016;

            /// <summary>
            /// Holding: 当前轴错误信息, Default: 0.
            /// </summary>
            public const ushort CurrentAxisErrorMSG = 1017;

            /// <summary>
            /// Holding: 当前轴目标位置设定[1], Default: 0.
            /// </summary>
            public const ushort CurrentAxisTargetPosition1 = 1018;

            /// <summary>
            /// Holding: 当前轴目标位置设定[2], Default: 0.
            /// </summary>
            public const ushort CurrentAxisTargetPosition2 = 1019;

            /// <summary>
            /// Holding: 当前轴目标速度设定[1], Default: 0.
            /// </summary>
            public const ushort CurrentAxisSpeed1 = 1020;

            /// <summary>
            /// Holding: 当前轴目标速度设定[2], Default: 0.
            /// </summary>
            public const ushort CurrentAxisSpeed2 = 1021;

            /// <summary>
            /// Holding: 当前轴当前实时位置[1], Default: 0.
            /// </summary>
            public const ushort CurrentAxiPosition1 = 1022;

            /// <summary>
            /// Holding: 当前轴当前实时位置[2], Default: 0.
            /// </summary>
            public const ushort CurrentAxiPosition2 = 1023;

            /// <summary>
            /// Holding: 运行模式选择, 全自动半自动 Default: 0.
            /// </summary>
            public const ushort SelectRunMode = 1032;

            /// <summary>
            /// Holding: 测试模式选择, 1 edge 2 surface 3 edge+surface Default: 0.
            /// </summary>
            public const ushort SelectTestMode = 1033;

            /// <summary>
            /// Holding: Edge当前测试slot, Default: 0.
            /// </summary>
            public const ushort EdgeCurrentTestSlot = 1034;

            /// <summary>
            /// Holding: Edge当前测试Cassette, Default: 0.
            /// </summary>
            public const ushort EdgeCurrentTestCassette = 1035;

            /// <summary>
            /// Holding: 测试完放的Slot位置, Default: 0.
            /// </summary>
            public const ushort AfterMeasurementSlotId = 1036;

            /// <summary>
            /// Holding: 测试完放的cassette位置, Default: 0.
            /// </summary>
            public const ushort AfterMeasurementCassetteId = 1037;

            /// <summary>
            /// Holding: WaferIDup光源亮度设定, Default: 0.
            /// </summary>
            public const ushort WaferIdUpLightness = 1038;

            /// <summary>
            /// Holding: WaferIDup光源亮度设定, Default: 0.
            /// </summary>
            public const ushort WaferIdDownLightness = 1039;

            /// <summary>
            /// Holding: CH1灯亮度, Default: 0.
            /// </summary>
            public const ushort Ch1Lightness = 1040;

            /// <summary>
            /// Holding: CH2灯亮度, Default: 0.
            /// </summary>
            public const ushort Ch2Lightness = 1041;

            /// <summary>
            /// Holding: CH3灯亮度, Default: 0.
            /// </summary>
            public const ushort Ch3Lightness = 1042;

            /// <summary>
            /// Holding: CH4灯亮度, Default: 0.
            /// </summary>
            public const ushort Ch4Lightness = 1043;

            /// <summary>
            /// Holding: BS线光源1亮度设定, Default: 0.
            /// </summary>
            public const ushort BS1Lightness = 1044;

            /// <summary>
            /// Holding: BS线光源2亮度设定, Default: 0.
            /// </summary>
            public const ushort BS2Lightness = 1045;

            /// <summary>
            /// Holding: LP1/SLOT选择[1], Default: 0.
            /// </summary>
            public const ushort LoadPort1SelectedSlot1 = 1048;

            /// <summary>
            /// Holding: LP1/SLOT选择[2], Default: 0.
            /// </summary>
            public const ushort LoadPort1SelectedSlot2 = 1049;

            /// <summary>
            /// Holding: LP2/SLOT选择[1], Default: 0.
            /// </summary>
            public const ushort LoadPort2SelectedSlot1 = 1050;

            /// <summary>
            /// Holding: LP2/SLOT选择[2], Default: 0.
            /// </summary>
            public const ushort LoadPort2SelectedSlot2 = 1051;

            /// <summary>
            /// Holding: LP3/SLOT选择[1], Default: 0.
            /// </summary>
            public const ushort LoadPort3SelectedSlot1 = 1052;

            /// <summary>
            /// Holding: LP3/SLOT选择[2], Default: 0.
            /// </summary>
            public const ushort LoadPort3SelectedSlot2 = 1053;

            /// <summary>
            /// Holding: LP4/SLOT选择[1], Default: 0.
            /// </summary>
            public const ushort LoadPort4SelectedSlot1 = 1054;

            /// <summary>
            /// Holding: LP4/SLOT选择[2], Default: 0.
            /// </summary>
            public const ushort LoadPort4SelectedSlot2 = 1055;

            /// <summary>
            /// Holding: Aligner当前检测SlotId, Default: .
            /// </summary>
            public const ushort AlignerCurrentTestSlot = 1056;

            /// <summary>
            /// Holding: Aligner当前检测CassetteId, Default: .
            /// </summary>
            public const ushort AlignerCurrentTestCassette = 1057;

            /// <summary>
            /// Holding: Surface当前检测SlotId, Default: .
            /// </summary>
            public const ushort SurfaceCurrentTestSlot = 1058;

            /// <summary>
            /// Holding: Surface当前检测CassetteId, Default: .
            /// </summary>
            public const ushort SurfaceCurrentTestCassette = 1059;

            /// <summary>
            /// Holding: RB任务号, Default: 0.
            /// </summary>
            public const ushort RobotTask = 1064;

            /// <summary>
            /// Holding: Arm1_Postion[1], Default: 0.
            /// </summary>
            public const ushort Arm1Pos1 = 1066;

            /// <summary>
            /// Holding: Arm1_Postion[2], Default: 0.
            /// </summary>
            public const ushort Arm1Pos2 = 1067;

            /// <summary>
            /// Holding: R_Postion[1], Default: 0.
            /// </summary>
            public const ushort RoundPos1 = 1068;

            /// <summary>
            /// Holding: R_Postion[2], Default: 0.
            /// </summary>
            public const ushort RoundPos2 = 1069;

            /// <summary>
            /// Holding: Arm2_Postion[1], Default: 0.
            /// </summary>
            public const ushort Arm2Pos1 = 1070;

            /// <summary>
            /// Holding: Arm2_Postion[2], Default: 0.
            /// </summary>
            public const ushort Arm2Pos2 = 1071;

            /// <summary>
            /// Holding: Z_Postion[1], Default: 0.
            /// </summary>
            public const ushort ZPos1 = 1072;

            /// <summary>
            /// Holding: Z_Postion[2], Default: 0.
            /// </summary>
            public const ushort ZPos2 = 1073;

            /// <summary>
            /// Holding: LP1任务号, Default: 0.
            /// </summary>
            public const ushort LoadPort1Task = 1080;

            /// <summary>
            /// Holding: LP2任务号, Default: 0.
            /// </summary>
            public const ushort LoadPort2Task = 1081;

            /// <summary>
            /// Holding: LP3任务号, Default: 0.
            /// </summary>
            public const ushort LoadPort3Task = 1082;

            /// <summary>
            /// Holding: LP4任务号, Default: 0.
            /// </summary>
            public const ushort LoadPort4Task = 1083;

            /// <summary>
            /// Holding: LP1MP结果[1], Default: 0.
            /// </summary>
            public const ushort LP1MPResult1 = 1084;

            /// <summary>
            /// Holding: LP1MP结果[2], Default: 0.
            /// </summary>
            public const ushort LP1MPResult2 = 1085;

            /// <summary>
            /// Holding: LP2MP结果[1], Default: 0.
            /// </summary>
            public const ushort LP2MPResult1 = 1086;

            /// <summary>
            /// Holding: LP2MP结果[2], Default: 0.
            /// </summary>
            public const ushort LP2MPResult2 = 1087;

            /// <summary>
            /// Holding: LP3MP结果[1], Default: 0.
            /// </summary>
            public const ushort LP3MPResult1 = 1088;

            /// <summary>
            /// Holding: LP3MP结果[2], Default: 0.
            /// </summary>
            public const ushort LP3MPResult2 = 1089;

            /// <summary>
            /// Holding: LP4MP结果[1], Default: 0.
            /// </summary>
            public const ushort LP4MPResult1 = 1090;

            /// <summary>
            /// Holding: LP4MP结果[2], Default: 0.
            /// </summary>
            public const ushort LP4MPResult2 = 1091;

            /// <summary>
            /// Holding: 设定自动换盒次数, Default: 0.
            /// </summary>
            public const ushort SetAutoCassetteChangeCount = 1092;

            /// <summary>
            /// Holding: 当前已换盒次数, Default: 0.
            /// </summary>
            public const ushort CurrentCassetteChangeCount = 1093;

            /// <summary>
            /// Holding: ALN任务号, Default: 0.
            /// </summary>
            public const ushort AlignerTask = 1096;

            /// <summary>
            /// Holding: Wafer停止角度, Default: 0.
            /// </summary>
            public const ushort AlignerAngle = 1097;

            /// <summary>
            /// Holding: 指定气缸ID, Default: 0.
            /// </summary>
            public const ushort SelectCylinderID = 1112;

            /// <summary>
            /// Holding: 选定气缸错误代码, Default: 0.
            /// </summary>
            public const ushort SelectCylinderErrCode = 1113;

            /// <summary>
            /// Holding: 选CassetteID1, Default: 0.
            /// </summary>
            public const ushort CassetteId11 = 1126;

            /// <summary>
            /// Holding: 选CassetteID2, Default: 0.
            /// </summary>
            public const ushort CassetteId12 = 1127;

            /// <summary>
            /// Holding: 选CassetteID3, Default: 0.
            /// </summary>
            /// <summary>
            /// Holding: 选CassetteID4, Default: 0.
            /// </summary>
            public const ushort CassetteId13 = 1128;

            /// <summary>
            /// Holding: 选CassetteID5, Default: 0.
            /// </summary>
            public const ushort CassetteId14 = 1129;

            /// <summary>
            /// Holding: 选CassetteID6, Default: 0.
            /// </summary>
            public const ushort CassetteId15 = 1130;

            /// <summary>
            /// Holding: 选CassetteID7, Default: 0.
            /// </summary>
            public const ushort CassetteId16 = 1131;

            /// <summary>
            /// Holding: 选CassetteID8, Default: 0.
            /// </summary>
            public const ushort CassetteId17 = 1132;

            /// <summary>
            /// Holding: 选CassetteID9, Default: 0.
            /// </summary>
            public const ushort CassetteId18 = 1133;

            /// <summary>
            /// Holding: 选CassetteID10, Default: 0.
            /// </summary>
            public const ushort CassetteId21 = 1134;

            /// <summary>
            /// Holding: 选CassetteID11, Default: 0.
            /// </summary>
            public const ushort CassetteId22 = 1135;

            /// <summary>
            /// Holding: 选CassetteID12, Default: 0.
            /// </summary>
            public const ushort CassetteId23 = 1136;

            /// <summary>
            /// Holding: 选CassetteID24, Default: 0.
            /// </summary>
            public const ushort CassetteId24 = 1137;

            /// <summary>
            /// Holding: 选CassetteID25, Default: 0.
            /// </summary>
            public const ushort CassetteId25 = 1138;

            /// <summary>
            /// Holding: 选CassetteID26, Default: 0.
            /// </summary>
            public const ushort CassetteId26 = 1139;

            /// <summary>
            /// Holding: 选CassetteID27, Default: 0.
            /// </summary>
            public const ushort CassetteId27 = 1140;

            /// <summary>
            /// Holding: 选CassetteID28, Default: 0.
            /// </summary>
            public const ushort CassetteId28 = 1141;

            /// <summary>
            /// Holding: 选CassetteID31, Default: 0.
            /// </summary>
            public const ushort CassetteId31 = 1142;

            /// <summary>
            /// Holding: 选CassetteID32, Default: 0.
            /// </summary>
            public const ushort CassetteId32 = 1143;

            /// <summary>
            /// Holding: 选CassetteID33, Default: 0.
            /// </summary>
            public const ushort CassetteId33 = 1144;

            /// <summary>
            /// Holding: 选CassetteID34, Default: 0.
            /// </summary>
            public const ushort CassetteId34 = 1145;

            /// <summary>
            /// Holding: 选CassetteID35, Default: 0.
            /// </summary>
            public const ushort CassetteId35 = 1146;

            /// <summary>
            /// Holding: 选CassetteID36, Default: 0.
            /// </summary>
            public const ushort CassetteId36 = 1147;

            /// <summary>
            /// Holding: 选CassetteID37, Default: 0.
            /// </summary>
            public const ushort CassetteId37 = 1148;

            /// <summary>
            /// Holding: 选CassetteID38, Default: 0.
            /// </summary>
            public const ushort CassetteId38 = 1149;

            /// <summary>
            /// Holding: 选CassetteID41, Default: 0.
            /// </summary>
            public const ushort CassetteId41 = 1150;

            /// <summary>
            /// Holding: 选CassetteID42, Default: 0.
            /// </summary>
            public const ushort CassetteId42 = 1151;

            /// <summary>
            /// Holding: 选CassetteID43, Default: 0.
            /// </summary>
            public const ushort CassetteId43 = 1152;

            /// <summary>
            /// Holding: 选CassetteID44, Default: 0.
            /// </summary>
            public const ushort CassetteId44 = 1153;

            /// <summary>
            /// Holding: 选CassetteID45, Default: 0.
            /// </summary>
            public const ushort CassetteId45 = 1154;

            /// <summary>
            /// Holding: 选CassetteID46, Default: 0.
            /// </summary>
            public const ushort CassetteId46 = 1155;

            /// <summary>
            /// Holding: 选CassetteID47, Default: 0.
            /// </summary>
            public const ushort CassetteId47 = 1156;

            /// <summary>
            /// Holding: 选CassetteID48, Default: 0.
            /// </summary>
            public const ushort CassetteId48 = 1157;

            /// <summary>
            /// Holding: 选CassetteID51, Default: 0.
            /// </summary>
            public const ushort RobotStatus = 1158;

            /// <summary>
            /// Holding: 选CassetteID51, Default: 0.
            /// </summary>
            public const ushort LoadPort1Status = 1159;

            /// <summary>
            /// Holding: 选CassetteID51, Default: 0.
            /// </summary>
            public const ushort LoadPort2Status = 1160;

            /// <summary>
            /// Holding: 选CassetteID51, Default: 0.
            /// </summary>
            public const ushort LoadPort3Status = 1161;

            /// <summary>
            /// Holding: 选CassetteID51, Default: 0.
            /// </summary>
            public const ushort LoadPort4Status = 1162;

            /// <summary>
            /// Holding: 选CassetteID51, Default: 0.
            /// </summary>
            public const ushort AlignerStatus = 1163;

            /// <summary>
            /// Holding: 选CassetteID51, Default: 0.
            /// </summary>
            public const ushort EdgeStatus = 1164;

            /// <summary>
            /// Holding: 选CassetteID51, Default: 0.
            /// </summary>
            public const ushort SurfaceStatus = 1165;

            /// <summary>
            /// Holding: 设置EdgeLightArch的亮度值，Default: 0.
            /// </summary>
            public const ushort EdgeLightArch = 1175;

            /// <summary>
            /// Holding: 设置EdgeLightDot的亮度值，Default: 0.
            /// </summary>
            public const ushort EdgeLightDot = 1176;

            /// <summary>
            /// Holding: 设置RecheckLightUp的亮度值，Default: 0.
            /// </summary>
            public const ushort RecheckLightUp = 1177;

            /// <summary>
            /// Holding: 设置RecheckLightDown的亮度值， Default: 0.
            /// </summary>
            public const ushort RecheckLightDown = 1178;
        }
    }
}
